# Generated by Django 6.0 on 2026-01-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="address",
        ),
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="email",
        ),
        migrations.RemoveField(
            model_name="category",
            name="phone",
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="categories.category",
                    ),
                ),
            ],
        ),
    ]
